[versions]
libphonenumber = "9.0.19"
sentry = "8.27.1"
rewrite = "3.17.0"
jsonassert = "1.5.3"
assertj = "3.27.6"
bean-matchers = "0.14"

[libraries]
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
sentry = { module = "io.sentry:sentry-logback", version.ref = "sentry" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
beanmatchers = { module = "com.google.code.bean-matchers:bean-matchers", version.ref = "bean-matchers" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
micronaut-application = { id = "io.micronaut.application", version = "4.6.1" }
micronaut-aot = { id = "io.micronaut.aot", version = "4.6.1" }
rewrite = { id = "org.openrewrite.rewrite", version = "7.22.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
sonarqube = { id = "org.sonarqube", version = "7.2.0.6526" }
